### ISSUE TITLE
fail to find symbol for a provided object literal

### ISSUE THREAD

**Issue by alexeagle** [angular/closure-to-dts#40]
js:
```
goog.provide('goog.color.names');

goog.color.names = {
    'aliceblue': '#f0f8ff',
    'antiquewhite': '#faebd7'
};
```

error:
```
java.lang.IllegalArgumentException: goog.provide not defined: goog.color.names
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:145)
	at com.google.javascript.cl2dts.DeclarationGenerator.produceDts(DeclarationGenerator.java:153)
```

in the debugger, can see
```
topScope.getOwnSlot("goog.color") -> Var goog.color{{names: {aliceblue: string, antiquewhite: string}}}
topScope.getOwnSlot("goog.color.names") -> null
topScope.getOwnSlot("goog.color.names.aliceblue") -> Var goog.color.names.aliceblue{string}
```

**Comment by alexeagle** [comment]
and
```
topScope.getAllSymbols() ->
...
32 = {TypedVar@2094} "Var goog{null}"
33 = {TypedVar@1633} "Var goog.color{{names: {aliceblue: string, antiquewhite: string}}}"
34 = {TypedVar@1635} "Var goog.color.names.aliceblue{string}"
35 = {TypedVar@2095} "Var goog.color.names.antiquewhite{string}"
```

**Comment by rkirov** [comment]
Wtf, if  "goog.color.names" is missing from symbols, how would a program typecheck ``` for (var c in goog.color.names)```?

**Comment by alexeagle** [comment]
note that adding a `@type` declaration on the declaration fixes this.

**Comment by MatrixFrog** [comment]
Yeah, just adding that `@type` seems like it might be a good short-term "fix" though there is likely a compiler-side fix that should eventually happen too.

**Comment by rkirov** [comment]
Closing this one as we "fixed" it by better typing the input Closure code.
